[package]
name = "probe-rs-lib"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "C ABI dynamic library (cdylib) to flash targets using probe-rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
probe-rs.workspace = true